name: alert_her
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  provider: ^6.1.2
  connectivity_plus: ^6.1.0
  go_router: ^15.0.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.14
  url_launcher: ^6.3.1
  country_phone_validator: ^1.0.1
  pinput: ^5.0.0
  translator: ^1.0.3+1
  in_app_purchase: ^3.2.0
  lottie: ^3.1.2
  country_picker: ^2.0.27
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^19.1.0
  shared_preferences: ^2.3.3
  showcaseview: ^4.0.1
  in_app_purchase_storekit:
  in_app_purchase_android: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - assets/lang/de.json
    - assets/lang/en.json
    - assets/lang/es.json
    - assets/lang/ro.json
    - assets/lang/th.json
    - assets/lang/vi.json
    - assets/lang/zh.json

  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Condensed.ttf
        - asset: assets/fonts/Roboto-BoldCondensed.ttf
        - asset: assets/fonts/Roboto-CondensedItalic.ttf
        - asset: assets/fonts/Roboto-BoldCondensedItalic.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf

    - family: meno_banner
      fonts:
        - asset: assets/fonts/MenoBanner-Black.otf
          weight: 400
        - asset: assets/fonts/MenoBanner-ExtraBold.otf
          weight: 700
